language: node_js
node_js:
  - "stable"
env:
  - CI=false
branches:
  only:
  - master
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "deploy@travis-ci.org"
  - "sed -i -E 's;\"homepage\": +?\"/\";\"homepage\": \"https://cool2645.github.io/orange-cheers/\";g' package.json"
install:
  - yarn install
script:
  - yarn build
after_success:
  - cd build
  - git init
  - git checkout --orphan gh-pages
  - git add -A
  - git commit -m "travis auto build"
  - git push --force https://$REPO_TOKEN@github.com/cool2645/orange-cheers.git gh-pages:gh-pages